name: myenv
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - dlib
  - numpy
  - pandas
  - Pillow
  - torch
  - torchvision
  - opencv
  - ipython
  - pip:
      - streamlit